[package]
name = "mini-linked-list"
version = "0.1.1"
edition = "2021"
description = "A package containing a minimal i32 LinkedList implementation"
license = "Apache-2.0" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
